services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: huuva_backend:${HUUVA_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      HUUVA_BACKEND_HOST: 0.0.0.0
      HUUVA_BACKEND_DB_HOST: huuva_backend-db
      HUUVA_BACKEND_DB_PORT: 5432
      HUUVA_BACKEND_DB_USER: huuva_backend
      HUUVA_BACKEND_DB_PASS: huuva_backend
      HUUVA_BACKEND_DB_BASE: huuva_backend

  db:
    image: postgres:16.3-bullseye
    hostname: huuva_backend-db
    environment:
      POSTGRES_PASSWORD: "huuva_backend"
      POSTGRES_USER: "huuva_backend"
      POSTGRES_DB: "huuva_backend"
    volumes:
      - huuva_backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U huuva_backend
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: huuva_backend:${HUUVA_BACKEND_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      HUUVA_BACKEND_DB_HOST: huuva_backend-db
      HUUVA_BACKEND_DB_PORT: 5432
      HUUVA_BACKEND_DB_USER: huuva_backend
      HUUVA_BACKEND_DB_PASS: huuva_backend
      HUUVA_BACKEND_DB_BASE: huuva_backend
    depends_on:
      db:
        condition: service_healthy



volumes:
  huuva_backend-db-data:
    name: huuva_backend-db-data
