services:
  app:
    build: .
    environment:
      - ENV_TYPE=dev
      - DEBUG=True
      - DATABASE_URL=postgresql://dev_user:dev_pass@postgres:5432/huuva_dev_db
      - SENTRY_DSN=
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: huuva_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
