name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-root
      - name: Run Pre-commit Lint Checks
        run: poetry run pre-commit run --all-files
      - name: Run Tests
        run: poetry run pytest
